### ISSUE TITLE
When plugging in a pack, UI shows 'no pack' then 'idle', why?

### ISSUE THREAD

**Issue by johncclayton** [johncclayton/electric#49]
![img_0129](https://cloud.githubusercontent.com/assets/1405394/22118530/7b26f79a-de78-11e6-9fce-dd4eed0c67ee.png)

**Comment by scornflake** [comment]
OK. The reason is that we use the per channel amp max to work out if we should show it or not.
Expectations were that the channel would be showing +40v in the case of the 410.

I need a couple of things from you:
a) What is the ‘pack voltage’ without the main charge lead connected, but with balance leads connected?
b) What is the ‘pack voltage’ then, without the balance leads disconnected? 



—
Neil Clayton
neil@cloudnine.net.nz

**Comment by scornflake** [comment]
oi. reply to this one please! gimme some data :)
Does it still happen for you?
